// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // === IMMEDIATE FIX: Replace with your actual Firebase values ===
  // Get these from: https://console.firebase.google.com/ → Project Settings → Your Android App
  
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCktnNuOijOciwjGUP1Xy3fa03FGcefCtw',
  appId: '1:533273867064:android:b7ea8bb276f838d69c07cd',
  messagingSenderId: '533273867064',
  projectId: 'shopp-5ee57',
  storageBucket: 'shopp-5ee57.appspot.com',
    measurementId: 'G-DEMO123456',
  );

  static const FirebaseOptions android = FirebaseOptions(
   apiKey: 'AIzaSyCktnNuOijOciwjGUP1Xy3fa03FGcefCtw',
  appId: '1:533273867064:android:b7ea8bb276f838d69c07cd',
  messagingSenderId: '533273867064',
  projectId: 'shopp-5ee57',
  storageBucket: 'shopp-5ee57.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCktnNuOijOciwjGUP1Xy3fa03FGcefCtw',
  appId: '1:533273867064:android:b7ea8bb276f838d69c07cd',
  messagingSenderId: '533273867064',
  projectId: 'shopp-5ee57',
  storageBucket: 'shopp-5ee57.appspot.com',
  );
static const FirebaseOptions macos = FirebaseOptions(
  apiKey: 'AIzaSyCktnNuOijOciwjGUP1Xy3fa03FGcefCtw',
  appId: '1:533273867064:android:b7ea8bb276f838d69c07cd',
  messagingSenderId: '533273867064',
  projectId: 'shopp-5ee57',
  storageBucket: 'shopp-5ee57.appspot.com',
);

}
